/* afterhours — etkinlik verisi (36 kayit). index 20'sini, serit sayfasi hepsini kullanir. */

const POSTERS = [

  { tur: "Konzert",    baslik: "A$AP Rocky",              meta: "Olympiahalle · 11.09.26 · 18:30",              metin: "An arena show built around one voice. Doors early, everyone seated until they aren't." },
  { tur: "Konzert",    baslik: "Nick Cave",                meta: "Olympiapark · 23.08 · open air",               metin: "The Bad Seeds outdoors, at dusk. Quiet enough that you hear the crowd breathing between songs." },
  { tur: "Konzert",    baslik: "Bonez MC & RAF Camora",    meta: "Olympiahalle · 21.12.26 · 20:00",              metin: "Palmen aus Plastik, ten years on. A December hall show that behaves like a summer one." },
  { tur: "Konzert",    baslik: "Thirty Seconds to Mars",   meta: "Olympiahalle · 12.04.27",                      metin: "Stadium rock at hall scale. Bring a voice you don't mind losing." },
  { tur: "Konzert",    baslik: "AnnenMayKantereit",        meta: "Olympiapark · 15—16.09",                       metin: "Two nights in a row, same park, different setlist. Sung back word for word either way." },
  { tur: "Festival",   baslik: "Elysium",                  meta: "Maxvorstadt · 12.09.26",                       metin: "Three stages, one night, no camping. A festival that fits inside a single walk home." },
  { tur: "Festival",   baslik: "Tollwood",                 meta: "Olympiapark · Sommer 2027",                    metin: "Three weeks of stages, kitchens and market stalls. Come for one act, stay for the field." },
  { tur: "Festival",   baslik: "Mondscheinexpress",        meta: "Bahnwärter Thiel · 19.11 — 23.12",             metin: "The winter counterpart: a month of short, cold, close-up nights between the containers." },
  { tur: "Festival",   baslik: "Isle of Summer",           meta: "Galopprennbahn Riem · 2027 TBA",               metin: "Open air on the old racecourse. Line-up lands in spring, tickets go before it does." },
  { tur: "Festival",   baslik: "Zamanand",                 meta: "München · 12.09 · 16:00",                      metin: "Starts in daylight and never quite admits it's a festival. Local bills, no headliner hierarchy." },
  { tur: "Rave",       baslik: "Blitz",                    meta: "Museumsinsel 1 · 23:59",                       metin: "CJ Bolland b2b The Advent, Polygonia after. Phones stay in pockets — the no-photo rule is the point." },
  { tur: "Rave",       baslik: "Rote Sonne × Bahnwärter",  meta: "29.08.26 · 12:00 — 06:00",                     metin: "Eighteen hours that start in the sun and end in a basement. One ticket, two places." },
  { tur: "Rave",       baslik: "Silo West",                meta: "München · 05.09 · 14:00",                       metin: "Narciss, Bambounou, B4ME. A day rave that sends you home before the last train, in theory." },
  { tur: "Rave",       baslik: "CFU Open Air",             meta: "Bahnwärter Thiel · 18.07 · 14:00",             metin: "Outside while it's warm, inside when it isn't. The same crowd moves between both all afternoon." },
  { tur: "Rave",       baslik: "Daytime Rave",             meta: "München · 24.10 · 17:00",                      metin: "Anna Reusch and Thomas Schumacher, finished by midnight. Built for people who like sleeping." },
  { tur: "Club Night", baslik: "Echonomist",               meta: "Pimpernel · 25.09 · 22:00",                     metin: "Staged inside a former cinema — the screen stays up, the seats don't. Sound follows the room." },
  { tur: "Club Night", baslik: "10 Years Blurred Vision",  meta: "München · 30.10 · 22:00",                      metin: "A decade of one collective, condensed into one night. Residents only, no guest slot." },
  { tur: "Club Night", baslik: "Legal × Blitz",            meta: "29.08 · Muallem",                              metin: "Two bookers sharing one floor. House early, techno late, the handover is the whole show." },
  { tur: "Club Night", baslik: "Bahnwärter Techno-Nacht",  meta: "Bahnwärter Thiel · 22:00",                     metin: "Moritz Minoa, Palastica, Sayuara. Stacked containers, low ceilings, nothing polished." },
  { tur: "Club Night", baslik: "Unterwelt",                meta: "Sunny Red · 02.10.26 · 22:00",                 metin: "Down one staircase at a time until the room stops getting bigger. Ends when it ends." },
  { tur: "Hausparty",  baslik: "Küchentisch",          meta: "Schwabing · 14.11 · 21:00",            metin: "Four rooms, one kitchen, and everyone ends up in the kitchen anyway. Bring something to share." },
  { tur: "Hausparty",  baslik: "3. Stock Links",       meta: "Haidhausen · 05.07 · 20:00",           metin: "Balcony party with string lights and a borrowed speaker. Quiet by two, that's the deal with the neighbours." },
  { tur: "Hausparty",  baslik: "Boxenturm",            meta: "Sendling · 19.09 · 22:00",             metin: "Someone stacked four cabinets in a backyard. The stack is the whole concept." },
  { tur: "Hausparty",  baslik: "Klingel 14",           meta: "Maxvorstadt · 28.11 · 22:00",          metin: "No address posted — you get the doorbell number and a name. Ring the right one." },
  { tur: "Hausparty",  baslik: "Plattenabend",         meta: "Giesing · 07.12",                      metin: "Vinyl only, everyone brings one record, nobody gets to hear their own twice." },
  { tur: "Hausparty",  baslik: "Vierter Stock",        meta: "Neuhausen · 21.02",                    metin: "Fourth floor, no lift, and the stairwell becomes the smoking area by midnight." },
  { tur: "Meetup",     baslik: "Zine Klub",            meta: "Glockenbach · 03.09 · 19:00",          metin: "Bring a page, leave with a stapled issue. First Tuesday of every month, no experience needed." },
  { tur: "Meetup",     baslik: "Kaffee & Karten",      meta: "Westend · Sonntags · 15:00",           metin: "Card games and too much coffee. Daylight only — it's over before anything else starts." },
  { tur: "Meetup",     baslik: "Nachtlinie",           meta: "ab Isartor · 18.10 · 18:00",           metin: "A guided night walk along the river and back through the old town. Ends at a bar, obviously." },
  { tur: "Meetup",     baslik: "Sprechstunde",         meta: "Untergiesing · Mittwochs · 19:30",     metin: "An open round table — you talk about what you're making, someone tells you what's wrong with it." },
  { tur: "Meetup",     baslik: "Riso Abend",           meta: "Schlachthofviertel · 09.10 · 18:00",   metin: "Two-colour risograph workshop. You leave with ink on your hands and forty prints." },
  { tur: "Meetup",     baslik: "Lange Tafel",          meta: "Alte Utting · 26.09 · 18:30",          metin: "One long table on a beached ship, strangers seated next to each other on purpose." },
  { tur: "Rave",       baslik: "Strobo",               meta: "Zenith Halle · 14.11 · 01:00",         metin: "Hector Oaks and Sara Landry. Fast, loud, and unapologetically bright — sit this one out if lights are a problem." },
  { tur: "Rave",       baslik: "Tunnelblick",          meta: "Tonhalle · 31.10",                     metin: "Twenty-four hours with no announced ending. People arrive in shifts." },
  { tur: "Club Night", baslik: "Spiegelsaal",          meta: "P1 · 06.12 · 23:00",                   metin: "Italo and disco under an actual mirror ball. The most fun you'll have taking nothing seriously." },
  { tur: "Club Night", baslik: "Pegel",                meta: "Milla Club · 11.10 · 22:00",           metin: "Live hardware sets, no laptops on stage. You watch the sound get built in front of you." },
];
