/* afterhours — the event data (36 records). The landing page uses 20 of
   them, the strip page uses all of them. */

const POSTERS = [

  { slug: "asap-rocky", kind: "Konzert",    title: "A$AP Rocky",              meta: "Olympiahalle · 11.09.26 · 18:30",              body: "An arena show built around one voice. Doors early, everyone seated until they aren't." },
  { slug: "nick-cave", kind: "Konzert",    title: "Nick Cave",                meta: "Olympiapark · 23.08 · open air",               body: "The Bad Seeds outdoors, at dusk. Quiet enough that you hear the crowd breathing between songs." },
  { slug: "bonez-mc-raf-camora", kind: "Konzert",    title: "Bonez MC & RAF Camora",    meta: "Olympiahalle · 21.12.26 · 20:00",              body: "Palmen aus Plastik, ten years on. A December hall show that behaves like a summer one." },
  { slug: "thirty-seconds-to-mars", kind: "Konzert",    title: "Thirty Seconds to Mars",   meta: "Olympiahalle · 12.04.27",                      body: "Stadium rock at hall scale. Bring a voice you don't mind losing." },
  { slug: "annenmaykantereit", kind: "Konzert",    title: "AnnenMayKantereit",        meta: "Olympiapark · 15—16.09",                       body: "Two nights in a row, same park, different setlist. Sung back word for word either way." },
  { slug: "elysium", kind: "Festival",   title: "Elysium",                  meta: "Maxvorstadt · 12.09.26",                       body: "Three stages, one night, no camping. A festival that fits inside a single walk home." },
  { slug: "tollwood", kind: "Festival",   title: "Tollwood",                 meta: "Olympiapark · Sommer 2027",                    body: "Three weeks of stages, kitchens and market stalls. Come for one act, stay for the field." },
  { slug: "mondscheinexpress", kind: "Festival",   title: "Mondscheinexpress",        meta: "Bahnwärter Thiel · 19.11 — 23.12",             body: "The winter counterpart: a month of short, cold, close-up nights between the containers." },
  { slug: "isle-of-summer", kind: "Festival",   title: "Isle of Summer",           meta: "Galopprennbahn Riem · 2027 TBA",               body: "Open air on the old racecourse. Line-up lands in spring, tickets go before it does." },
  { slug: "zamanand", kind: "Festival",   title: "Zamanand",                 meta: "München · 12.09 · 16:00",                      body: "Starts in daylight and never quite admits it's a festival. Local bills, no headliner hierarchy." },
  { slug: "blitz", kind: "Rave",       title: "Blitz",                    meta: "Museumsinsel 1 · 23:59",                       body: "CJ Bolland b2b The Advent, Polygonia after. Phones stay in pockets — the no-photo rule is the point." },
  { slug: "rote-sonne-bahnwarter", kind: "Rave",       title: "Rote Sonne × Bahnwärter",  meta: "29.08.26 · 12:00 — 06:00",                     body: "Eighteen hours that start in the sun and end in a basement. One ticket, two places." },
  { slug: "silo-west", kind: "Rave",       title: "Silo West",                meta: "München · 05.09 · 14:00",                       body: "Narciss, Bambounou, B4ME. A day rave that sends you home before the last train, in theory." },
  { slug: "cfu-open-air", kind: "Rave",       title: "CFU Open Air",             meta: "Bahnwärter Thiel · 18.07 · 14:00",             body: "Outside while it's warm, inside when it isn't. The same crowd moves between both all afternoon." },
  { slug: "daytime-rave", kind: "Rave",       title: "Daytime Rave",             meta: "München · 24.10 · 17:00",                      body: "Anna Reusch and Thomas Schumacher, finished by midnight. Built for people who like sleeping." },
  { slug: "echonomist", kind: "Club Night", title: "Echonomist",               meta: "Pimpernel · 25.09 · 22:00",                     body: "Staged inside a former cinema — the screen stays up, the seats don't. Sound follows the room." },
  { slug: "10-years-blurred-vision", kind: "Club Night", title: "10 Years Blurred Vision",  meta: "München · 30.10 · 22:00",                      body: "A decade of one collective, condensed into one night. Residents only, no guest slot." },
  { slug: "legal-blitz", kind: "Club Night", title: "Legal × Blitz",            meta: "29.08 · Muallem",                              body: "Two bookers sharing one floor. House early, techno late, the handover is the whole show." },
  { slug: "bahnwarter-techno-nacht", kind: "Club Night", title: "Bahnwärter Techno-Nacht",  meta: "Bahnwärter Thiel · 22:00",                     body: "Moritz Minoa, Palastica, Sayuara. Stacked containers, low ceilings, nothing polished." },
  { slug: "unterwelt", kind: "Club Night", title: "Unterwelt",                meta: "Sunny Red · 02.10.26 · 22:00",                 body: "Down one staircase at a time until the room stops getting bigger. Ends when it ends." },
  { slug: "kuchentisch", kind: "Hausparty",  title: "Küchentisch",          meta: "Schwabing · 14.11 · 21:00",            body: "Four rooms, one kitchen, and everyone ends up in the kitchen anyway. Bring something to share." },
  { slug: "3-stock-links", kind: "Hausparty",  title: "3. Stock Links",       meta: "Haidhausen · 05.07 · 20:00",           body: "Balcony party with string lights and a borrowed speaker. Quiet by two, that's the deal with the neighbours." },
  { slug: "boxenturm", kind: "Hausparty",  title: "Boxenturm",            meta: "Sendling · 19.09 · 22:00",             body: "Someone stacked four cabinets in a backyard. The stack is the whole concept." },
  { slug: "klingel-14", kind: "Hausparty",  title: "Klingel 14",           meta: "Maxvorstadt · 28.11 · 22:00",          body: "No address posted — you get the doorbell number and a name. Ring the right one." },
  { slug: "plattenabend", kind: "Hausparty",  title: "Plattenabend",         meta: "Giesing · 07.12",                      body: "Vinyl only, everyone brings one record, nobody gets to hear their own twice." },
  { slug: "vierter-stock", kind: "Hausparty",  title: "Vierter Stock",        meta: "Neuhausen · 21.02",                    body: "Fourth floor, no lift, and the stairwell becomes the smoking area by midnight." },
  { slug: "zine-klub", kind: "Meetup",     title: "Zine Klub",            meta: "Glockenbach · 03.09 · 19:00",          body: "Bring a page, leave with a stapled issue. First Tuesday of every month, no experience needed." },
  { slug: "kaffee-karten", kind: "Meetup",     title: "Kaffee & Karten",      meta: "Westend · Sonntags · 15:00",           body: "Card games and too much coffee. Daylight only — it's over before anything else starts." },
  { slug: "nachtlinie", kind: "Meetup",     title: "Nachtlinie",           meta: "ab Isartor · 18.10 · 18:00",           body: "A guided night walk along the river and back through the old town. Ends at a bar, obviously." },
  { slug: "sprechstunde", kind: "Meetup",     title: "Sprechstunde",         meta: "Untergiesing · Mittwochs · 19:30",     body: "An open round table — you talk about what you're making, someone tells you what's wrong with it." },
  { slug: "riso-abend", kind: "Meetup",     title: "Riso Abend",           meta: "Schlachthofviertel · 09.10 · 18:00",   body: "Two-colour risograph workshop. You leave with ink on your hands and forty prints." },
  { slug: "lange-tafel", kind: "Meetup",     title: "Lange Tafel",          meta: "Alte Utting · 26.09 · 18:30",          body: "One long table on a beached ship, strangers seated next to each other on purpose." },
  { slug: "strobo", kind: "Rave",       title: "Strobo",               meta: "Zenith Halle · 14.11 · 01:00",         body: "Hector Oaks and Sara Landry. Fast, loud, and unapologetically bright — sit this one out if lights are a problem." },
  { slug: "tunnelblick", kind: "Rave",       title: "Tunnelblick",          meta: "Tonhalle · 31.10",                     body: "Twenty-four hours with no announced ending. People arrive in shifts." },
  { slug: "spiegelsaal", kind: "Club Night", title: "Spiegelsaal",          meta: "P1 · 06.12 · 23:00",                   body: "Italo and disco under an actual mirror ball. The most fun you'll have taking nothing seriously." },
  { slug: "pegel", kind: "Club Night", title: "Pegel",                meta: "Milla Club · 11.10 · 22:00",           body: "Live hardware sets, no laptops on stage. You watch the sound get built in front of you." },
];
