#!/usr/bin/env python3
"""afterhours — build the three dictionaries, and refuse a half-translated one.

The words live in lang/src/*.json, all three languages side by side:

    { "nav.explore": { "en": "explore", "de": "entdecken", "tr": "keşfet" } }

A value is a string, or a list of strings (content pools). This writes
lang/en.js, lang/de.js and lang/tr.js — what the pages actually load —
and checks what the browser would never show:

  1. every key carries en, de and tr, none of them empty, and a list has
     the same length in all three;
  2. no key is defined in two files;
  3. the {placeholders} of a translation are the ones the english has;
  4. every key the pages ask for (data-i18n, data-i18n-html,
     data-i18n-attr) and every literal key the scripts ask for
     (AH.t("…"), AH.tn("…")) exists.

    python3 tools-lang.py           build + check
    python3 tools-lang.py --check   check only, write nothing (CI)

Exit 0 clean, exit 1 with a list.
"""
import json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent
SRC = ROOT / "lang" / "src"
LANGS = ["en", "de", "tr"]
SKIP_DIRS = {".git", "backend", "node_modules", "app", "vendor", "lang"}
check_only = "--check" in sys.argv

problems = []
words = {}
origin = {}

for part in sorted(SRC.glob("*.json")):
    try:
        data = json.loads(part.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        problems.append(f"{part.name}: not valid json ({e})")
        continue
    for key, entry in data.items():
        if key in words:
            problems.append(f"{part.name}: {key} is already defined in {origin[key]}")
            continue
        words[key] = entry
        origin[key] = part.name

PLACE = re.compile(r"\{(\w+)\}")


def places(value):
    if isinstance(value, list):
        return sorted({p for v in value for p in PLACE.findall(str(v))})
    return sorted(set(PLACE.findall(str(value))))


for key, entry in words.items():
    where = f"{origin[key]}: {key}"
    if not isinstance(entry, dict):
        problems.append(f"{where} is not an object of languages")
        continue
    for lang in LANGS:
        value = entry.get(lang)
        if value is None or value == "" or value == []:
            # an english empty string is a real value in a few status maps
            if value == "" and all(entry.get(l) == "" for l in LANGS):
                continue
            problems.append(f"{where} has no {lang}")
    en = entry.get("en")
    for lang in ("de", "tr"):
        value = entry.get(lang)
        if value is None:
            continue
        if isinstance(en, list) != isinstance(value, list):
            problems.append(f"{where}: {lang} is a different shape than en")
        elif isinstance(en, list) and len(en) != len(value):
            problems.append(f"{where}: {lang} has {len(value)} items, en has {len(en)}")
        if places(en) != places(value) and not isinstance(en, list):
            problems.append(f"{where}: {lang} placeholders {places(value)} != en {places(en)}")

# ------------------------------------------------- what the site asks for


def site_files(pattern):
    return [p for p in ROOT.rglob(pattern)
            if not (set(p.relative_to(ROOT).parts) & SKIP_DIRS)]


def known(key):
    return key in words or (key + ".other") in words


asked = 0
for page in site_files("*.html"):
    text = page.read_text(encoding="utf-8")
    keys = re.findall(r'data-i18n(?:-html)?="([^"]+)"', text)
    for group in re.findall(r'data-i18n-attr="([^"]+)"', text):
        for pair in group.split(";"):
            if ":" in pair:
                keys.append(pair.split(":", 1)[1].strip())
    for key in keys:
        asked += 1
        if key not in words:
            problems.append(f"{page.relative_to(ROOT)}: asks for {key}, which nobody defined")

CALL = re.compile(r'\b(?:AH\.)?(tn?)\(\s*(["\'])([A-Za-z0-9_.\-]+)\2')
for script in site_files("*.js"):
    if script.name in ("i18n.js", "knob.js"):
        continue
    text = script.read_text(encoding="utf-8")
    for kind, _, key in CALL.findall(text):
        if "." not in key and key not in words:
            continue          # t("x") of some other library, not ours
        asked += 1
        if key.endswith("."):
            continue          # a prefix the script completes: t("type." + slug)
        if kind == "tn":
            if (key + ".other") not in words:
                problems.append(f"{script.relative_to(ROOT)}: tn({key}) has no {key}.other")
        elif not known(key):
            problems.append(f"{script.relative_to(ROOT)}: asks for {key}, which nobody defined")

# --------------------------------------------------------------- write

if not check_only and not problems:
    for lang in LANGS:
        table = {k: words[k][lang] for k in sorted(words)}
        body = json.dumps(table, ensure_ascii=False, indent=0, separators=(",", ":"))
        out = (
            "/* afterhours — the words, " + lang + ". GENERATED by tools-lang.py from\n"
            "   lang/src/*.json; edit those, not this. */\n"
            "window.AH_LANG = window.AH_LANG || {};\n"
            "window.AH_LANG." + lang + " = " + body + ";\n"
        )
        (ROOT / "lang" / f"{lang}.js").write_text(out, encoding="utf-8")

if problems:
    print(f"{len(problems)} problem(s):")
    for p in problems:
        print("  ·", p)
    sys.exit(1)

print(f"{len(words)} keys × {len(LANGS)} languages, {asked} requests from the site — clean"
      + ("" if check_only else "; lang/en.js, de.js, tr.js written"))
