-- afterhours — "who is this?" for 18 nights in Munich (07.10.2026)
--
-- A one-shot for the LIVE project, after 40_event_about.sql. The texts were
-- written from the Wikipedia summary of each act (nothing added from elsewhere)
-- and read against it once more; three searches that landed on the wrong page
-- (Neunundneunzig, Undeath, Gurriers) were left out, as were the acts without a
-- page. Nights are found by slug; a night that is gone is skipped.
--
-- In the Supabase panel: SQL Editor → New query → paste → Run.

insert into public.event_about (event_id, lang, name, kicker, who, facts, source_url)
select e.id, v.lang, v.name, v.kicker, v.who, v.facts, v.source_url
from (values
  ('lake-street-dive-2026-european-tour-0360e37f', 'tr', 'Lake Street Dive', 'amerikan grup · 2004, boston', 'Boston''daki New England Conservatory''de, yani bir müzik okulunda tanışan dört öğrencinin kurduğu grup. Tek bir türe sığmıyorlar. Bugün Brooklyn''de yaşıyorlar ve sık sık Avrupa''ya turneye geliyorlar.', array['Grup bir konservatuvar sınıfından çıktı.', 'Klavyeci Akie Bermiss gruba önce turnede katıldı, 2018''deki Free Yourself Up albümünde resmen üye oldu.']::text[], 'https://en.wikipedia.org/wiki/Lake_Street_Dive'),
  ('lake-street-dive-2026-european-tour-0360e37f', 'en', 'Lake Street Dive', 'american band · 2004, boston', 'Four students who met at the New England Conservatory, a music school in Boston, started the band. They don''t fit one genre. Today they live in Brooklyn and tour Europe often.', array['The band came out of a conservatory class.', 'Keyboardist Akie Bermiss joined on tour first and became a member on the 2018 album Free Yourself Up.']::text[], 'https://en.wikipedia.org/wiki/Lake_Street_Dive'),
  ('lake-street-dive-2026-european-tour-0360e37f', 'de', 'Lake Street Dive', 'us-band · 2004, boston', 'Vier Studierende, die sich am New England Conservatory, einer Musikhochschule in Boston, kennengelernt haben, gründeten die Band. Sie passen in kein einzelnes Genre. Heute leben sie in Brooklyn und touren oft durch Europa.', array['Die Band kommt aus einer Konservatoriumsklasse.', 'Keyboarder Akie Bermiss kam erst auf Tour dazu und wurde mit dem Album Free Yourself Up (2018) Mitglied.']::text[], 'https://en.wikipedia.org/wiki/Lake_Street_Dive'),
  ('murda-uzay-tour-3be8f956', 'tr', 'Murda', 'türk-hollandalı rapçi', 'Asıl adı Önder Doğan. Amsterdam-Noord''da doğdu, çocukken Madrid''e, oradan İstanbul''a taşındı. Hip-hop''u kuzeni sayesinde keşfetti.', array['Annesi ve babası tiyatrocu.', 'Ezhel ve MERO ile birçok şarkıda birlikte çalıştı.']::text[], 'https://en.wikipedia.org/wiki/Murda_(rapper)'),
  ('murda-uzay-tour-3be8f956', 'en', 'Murda', 'turkish-dutch rapper', 'His real name is Önder Doğan. Born in Amsterdam-Noord, he moved to Madrid as a child and then to Istanbul. He found hip-hop through his cousin.', array['Both his parents work in theatre.', 'He has made many songs with Ezhel and MERO.']::text[], 'https://en.wikipedia.org/wiki/Murda_(rapper)'),
  ('murda-uzay-tour-3be8f956', 'de', 'Murda', 'türkisch-niederländischer rapper', 'Sein echter Name ist Önder Doğan. Geboren in Amsterdam-Noord, zog er als Kind nach Madrid und dann nach Istanbul. Zum Hip-Hop kam er über seinen Cousin.', array['Seine Eltern arbeiten beide am Theater.', 'Er hat viele Songs mit Ezhel und MERO gemacht.']::text[], 'https://en.wikipedia.org/wiki/Murda_(rapper)'),
  ('yaelokre-yaelokretour-3b52e567', 'tr', 'Yaelokre', 'filipinli-izlandalı şarkı yazarı · folk', 'Keath Ósk''un hikâye anlatan folk projesi.', array['İlk şarkılar 2024''ün başında çıktı; Temmuz''da "Harpy Hare" TikTok''ta patladı.', 'Aynı yıl Spotify''ın küresel viral listesinde birinci oldu.']::text[], 'https://en.wikipedia.org/wiki/Yaelokre'),
  ('yaelokre-yaelokretour-3b52e567', 'en', 'Yaelokre', 'filipino-icelandic songwriter · folk', 'Keath Ósk''s storytelling folk project.', array['The first songs came out in early 2024; in July "Harpy Hare" blew up on TikTok.', 'The same year it topped Spotify''s global viral chart.']::text[], 'https://en.wikipedia.org/wiki/Yaelokre'),
  ('yaelokre-yaelokretour-3b52e567', 'de', 'Yaelokre', 'philippinisch-isländisch · folk', 'Das erzählende Folk-Projekt von Keath Ósk.', array['Die ersten Songs erschienen Anfang 2024; im Juli ging "Harpy Hare" auf TikTok durch die Decke.', 'Im selben Jahr stand der Song auf Platz eins der globalen Spotify-Viral-Charts.']::text[], 'https://en.wikipedia.org/wiki/Yaelokre'),
  ('king-woman-16d054b4', 'tr', 'King Woman', 'doom metal · san francisco', 'Şarkıcı ve gitarist Kristina Esfandiari''nin grubu. Ağır, yavaş ve karanlık: doom metal.', array['Sözlerin çoğu Esfandiari''nin çocukluğunu geçirdiği, tarikat benzeri karizmatik bir Hristiyan topluluğu anlatıyor.', 'Esfandiari bu grubun arasında, bambaşka türlerde başka projeler de yürütüyor.']::text[], 'https://en.wikipedia.org/wiki/King_Woman'),
  ('king-woman-16d054b4', 'en', 'King Woman', 'doom metal · san francisco', 'The band of singer and guitarist Kristina Esfandiari. Heavy, slow and dark: doom metal.', array['Most lyrics are about Esfandiari''s childhood in a cult-like charismatic Christian community.', 'Between albums Esfandiari runs other projects in very different genres.']::text[], 'https://en.wikipedia.org/wiki/King_Woman'),
  ('king-woman-16d054b4', 'de', 'King Woman', 'doom metal · san francisco', 'Die Band von Sängerin und Gitarristin Kristina Esfandiari. Schwer, langsam und dunkel: Doom Metal.', array['Die meisten Texte handeln von Esfandiaris Kindheit in einer sektenähnlichen charismatischen christlichen Gemeinde.', 'Zwischen den Alben macht Esfandiari Projekte in ganz anderen Genres.']::text[], 'https://en.wikipedia.org/wiki/King_Woman'),
  ('don-toliver-nitrous-octane-world-tour-leg-2-f189161a', 'tr', 'Don Toliver', 'rapçi ve şarkıcı · houston', 'Houston''lı rapçi ve şarkıcı. Travis Scott''ın plak şirketi Cactus Jack''in yıldızlarından.', array['İlk mixtape''i Donny Womack, Travis Scott''ın Astroworld albümünden bir gün önce çıktı; Astroworld''de o da vardı.', 'Bir hafta sonra Cactus Jack ile anlaştı.']::text[], 'https://en.wikipedia.org/wiki/Don_Toliver'),
  ('don-toliver-nitrous-octane-world-tour-leg-2-f189161a', 'en', 'Don Toliver', 'rapper and singer · houston', 'A rapper and singer from Houston, one of the stars of Travis Scott''s label Cactus Jack.', array['His first mixtape, Donny Womack, came out one day before Travis Scott''s Astroworld, which he was on.', 'A week later he signed with Cactus Jack.']::text[], 'https://en.wikipedia.org/wiki/Don_Toliver'),
  ('don-toliver-nitrous-octane-world-tour-leg-2-f189161a', 'de', 'Don Toliver', 'rapper und sänger · houston', 'Rapper und Sänger aus Houston, einer der Stars von Travis Scotts Label Cactus Jack.', array['Sein erstes Mixtape, Donny Womack, erschien einen Tag vor Travis Scotts Astroworld, auf dem er zu hören ist.', 'Eine Woche später unterschrieb er bei Cactus Jack.']::text[], 'https://en.wikipedia.org/wiki/Don_Toliver'),
  ('arlo-parks-desire-tour-59f3ff27', 'tr', 'Arlo Parks', 'şarkıcı ve söz yazarı · londra', 'İngiliz şarkıcı ve söz yazarı; asıl adı Anaïs Oluwatoyin Estelle Marinho.', array['İlk albümü Collapsed in Sunbeams (2021) İngiltere listesinde üçüncü oldu.', 'Aynı albümle Mercury Prize''ı kazandı.']::text[], 'https://en.wikipedia.org/wiki/Arlo_Parks'),
  ('arlo-parks-desire-tour-59f3ff27', 'en', 'Arlo Parks', 'singer-songwriter · london', 'An English singer and songwriter; her real name is Anaïs Oluwatoyin Estelle Marinho.', array['Her first album, Collapsed in Sunbeams (2021), reached number three in the UK.', 'It won the Mercury Prize.']::text[], 'https://en.wikipedia.org/wiki/Arlo_Parks'),
  ('arlo-parks-desire-tour-59f3ff27', 'de', 'Arlo Parks', 'singer-songwriterin · london', 'Englische Sängerin und Songwriterin; ihr echter Name ist Anaïs Oluwatoyin Estelle Marinho.', array['Ihr erstes Album, Collapsed in Sunbeams (2021), kam in Großbritannien auf Platz drei.', 'Es gewann den Mercury Prize.']::text[], 'https://en.wikipedia.org/wiki/Arlo_Parks'),
  ('polyphia-be-not-afraid-world-tour-f41c593a', 'tr', 'Polyphia', 'progresif rock · texas', 'Teksas''tan dört kişilik bir rock grubu: iki gitarist (Tim Henson, Scott LePage), bas ve davul.', array['Metal olarak başladılar, sonra elektronik ve hip-hop''la karışan progresif bir sese geçtiler.', '2010''da Plano''da kuruldular.']::text[], 'https://en.wikipedia.org/wiki/Polyphia'),
  ('polyphia-be-not-afraid-world-tour-f41c593a', 'en', 'Polyphia', 'progressive rock · texas', 'A four-piece rock band from Texas: two guitarists (Tim Henson, Scott LePage), bass and drums.', array['They started out as metal and moved to a progressive sound mixed with electronic music and hip-hop.', 'They formed in Plano in 2010.']::text[], 'https://en.wikipedia.org/wiki/Polyphia'),
  ('polyphia-be-not-afraid-world-tour-f41c593a', 'de', 'Polyphia', 'progressive rock · texas', 'Eine vierköpfige Rockband aus Texas: zwei Gitarristen (Tim Henson, Scott LePage), Bass und Schlagzeug.', array['Angefangen haben sie mit Metal, dann kam ein progressiver Sound mit Elektronik und Hip-Hop.', 'Gegründet 2010 in Plano.']::text[], 'https://en.wikipedia.org/wiki/Polyphia'),
  ('novulent-live-in-europe-2026-d6839636', 'tr', 'Novulent', 'şarkıcı ve söz yazarı · dallas', 'Dallas''tan bir müzisyen, şarkıcı ve söz yazarı.', array['2023''te çıkan "Savior" ve "Scars" TikTok''ta viral oldu.', '"Scars" Amerika''da altın plak aldı; ardından 2024''te Capitol Records ile anlaştı.']::text[], 'https://en.wikipedia.org/wiki/Novulent'),
  ('novulent-live-in-europe-2026-d6839636', 'en', 'Novulent', 'singer-songwriter · dallas', 'A musician, singer and songwriter from Dallas.', array['"Savior" and "Scars", both from 2023, went viral on TikTok.', '"Scars" went gold in the US; in 2024 came a deal with Capitol Records.']::text[], 'https://en.wikipedia.org/wiki/Novulent'),
  ('novulent-live-in-europe-2026-d6839636', 'de', 'Novulent', 'singer-songwriter · dallas', 'Musiker, Sänger und Songwriter aus Dallas.', array['"Savior" und "Scars" aus 2023 gingen auf TikTok viral.', '"Scars" bekam in den USA Gold; 2024 folgte ein Vertrag mit Capitol Records.']::text[], 'https://en.wikipedia.org/wiki/Novulent'),
  ('noah-kahan-the-great-divide-tour-feccccc0', 'tr', 'Noah Kahan', 'şarkıcı ve söz yazarı · abd', 'Amerikalı şarkıcı ve söz yazarı. Büyük çıkışı 2022''deki Stick Season albümüyle geldi.', array['2023''te En İyi Yeni Sanatçı dalında Grammy''ye aday oldu.', '2026''daki dördüncü albümü The Great Divide, bir rock albümü için dinlenme ve plak satışında rekor kırarak bir numaradan girdi; bu tur o albümün turu.']::text[], 'https://en.wikipedia.org/wiki/Noah_Kahan'),
  ('noah-kahan-the-great-divide-tour-feccccc0', 'en', 'Noah Kahan', 'singer-songwriter · usa', 'An American singer and songwriter. The breakthrough came with Stick Season in 2022.', array['In 2023 he was nominated for the Grammy for Best New Artist.', 'His fourth album, The Great Divide (2026), entered at number one with record streaming and vinyl sales for a rock album; this is its tour.']::text[], 'https://en.wikipedia.org/wiki/Noah_Kahan'),
  ('noah-kahan-the-great-divide-tour-feccccc0', 'de', 'Noah Kahan', 'singer-songwriter · usa', 'US-amerikanischer Sänger und Songwriter. Der Durchbruch kam 2022 mit Stick Season.', array['2023 war er für den Grammy als bester neuer Künstler nominiert.', 'Sein viertes Album, The Great Divide (2026), stieg mit Rekordzahlen bei Streams und Vinyl für ein Rockalbum auf Platz eins ein; das ist die Tour dazu.']::text[], 'https://en.wikipedia.org/wiki/Noah_Kahan'),
  ('kodaline-farewell-tour-2ea5c102', 'tr', 'Kodaline', 'irlandalı rock grubu', 'Dört kişilik İrlandalı rock grubu. Bu tur bir veda turu.', array['İlk adları 21 Demands''ti.', '2012''de müzikleri değişince adlarını da Kodaline yaptılar.']::text[], 'https://en.wikipedia.org/wiki/Kodaline'),
  ('kodaline-farewell-tour-2ea5c102', 'en', 'Kodaline', 'irish rock band', 'A four-piece Irish rock band. This is a farewell tour.', array['Their first name was 21 Demands.', 'In 2012, as their music changed, they became Kodaline.']::text[], 'https://en.wikipedia.org/wiki/Kodaline'),
  ('kodaline-farewell-tour-2ea5c102', 'de', 'Kodaline', 'irische rockband', 'Eine vierköpfige irische Rockband. Das ist eine Abschiedstour.', array['Ihr erster Name war 21 Demands.', '2012, als sich ihre Musik änderte, wurden sie zu Kodaline.']::text[], 'https://en.wikipedia.org/wiki/Kodaline'),
  ('fkj-tyber-tour-b68be2c0', 'tr', 'FKJ', 'çok enstrümanlı müzisyen · fransa', 'FKJ, French Kiwi Juice''un kısaltması; asıl adı Vincent Fenton, Tours şehrinden.', array['Sahnede tek başına: çaldığı her şeyi o anda kaydedip üst üste bindiriyor (Ableton Live ile loop).', 'İlk albümünün adı da kendi adı: French Kiwi Juice (2017).']::text[], 'https://en.wikipedia.org/wiki/French_Kiwi_Juice'),
  ('fkj-tyber-tour-b68be2c0', 'en', 'FKJ', 'multi-instrumentalist · france', 'FKJ stands for French Kiwi Juice; his real name is Vincent Fenton, from the city of Tours.', array['On stage he is alone: he records everything he plays on the spot and layers it (looping in Ableton Live).', 'His first album carries his name: French Kiwi Juice (2017).']::text[], 'https://en.wikipedia.org/wiki/French_Kiwi_Juice'),
  ('fkj-tyber-tour-b68be2c0', 'de', 'FKJ', 'multiinstrumentalist · frankreich', 'FKJ steht für French Kiwi Juice; sein echter Name ist Vincent Fenton, aus der Stadt Tours.', array['Auf der Bühne ist er allein: Er nimmt alles, was er spielt, sofort auf und schichtet es übereinander (Loops in Ableton Live).', 'Sein erstes Album trägt seinen Namen: French Kiwi Juice (2017).']::text[], 'https://en.wikipedia.org/wiki/French_Kiwi_Juice'),
  ('placebo-30th-anniversary-tour-741ac673', 'tr', 'Placebo', 'alternatif rock · londra', '1994''te Londra''da kurulan alternatif rock grubu. Bu tur grubun 30. yıl turu.', array['Brian Molko ve Stefan Olsdal en başından beri gruptalar.', 'Yıllar içinde üç farklı kalıcı davulcuyla çaldılar.']::text[], 'https://en.wikipedia.org/wiki/Placebo_(band)'),
  ('placebo-30th-anniversary-tour-741ac673', 'en', 'Placebo', 'alternative rock · london', 'An alternative rock band formed in London in 1994. This is their 30th anniversary tour.', array['Brian Molko and Stefan Olsdal have been there from the start.', 'Over the years they have played with three full-time drummers.']::text[], 'https://en.wikipedia.org/wiki/Placebo_(band)'),
  ('placebo-30th-anniversary-tour-741ac673', 'de', 'Placebo', 'alternative rock · london', 'Eine Alternative-Rock-Band, 1994 in London gegründet. Das ist die Tour zum 30-jährigen Jubiläum.', array['Brian Molko und Stefan Olsdal sind von Anfang an dabei.', 'Über die Jahre hatten sie drei feste Schlagzeuger.']::text[], 'https://en.wikipedia.org/wiki/Placebo_(band)'),
  ('the-script-man-in-the-arena-tour-2026-ac59d456', 'tr', 'The Script', 'pop rock · dublin', '2001''de Dublin''de kurulan pop rock grubu.', array['İlk albümleri The Script (2008) hem İrlanda''da hem İngiltere''de bir numara oldu.', 'Kurucu gitarist Mark Sheehan 2023''te hayatını kaybetti.']::text[], 'https://en.wikipedia.org/wiki/The_Script'),
  ('the-script-man-in-the-arena-tour-2026-ac59d456', 'en', 'The Script', 'pop rock · dublin', 'A pop rock band formed in Dublin in 2001.', array['Their first album, The Script (2008), went to number one in Ireland and the UK.', 'Founding guitarist Mark Sheehan died in 2023.']::text[], 'https://en.wikipedia.org/wiki/The_Script'),
  ('the-script-man-in-the-arena-tour-2026-ac59d456', 'de', 'The Script', 'pop rock · dublin', 'Eine Pop-Rock-Band, 2001 in Dublin gegründet.', array['Ihr erstes Album, The Script (2008), kam in Irland und Großbritannien auf Platz eins.', 'Gründungsgitarrist Mark Sheehan starb 2023.']::text[], 'https://en.wikipedia.org/wiki/The_Script'),
  ('rea-garvey-s-christmas-calling-3a9bb663', 'tr', 'Rea Garvey', 'irlandalı şarkıcı · almanya', 'Almanya''da yaşayan İrlandalı şarkıcı. Bu gece Noel konseri.', array['11 yıl boyunca Reamonn grubunun solistiydi.', '2011''den beri solo; rock''tan elektro-pop''a geçti.']::text[], 'https://en.wikipedia.org/wiki/Rea_Garvey'),
  ('rea-garvey-s-christmas-calling-3a9bb663', 'en', 'Rea Garvey', 'irish singer · germany', 'An Irish singer who lives in Germany. Tonight is a Christmas show.', array['For 11 years he fronted the band Reamonn.', 'Solo since 2011, moving from rock to electro-pop.']::text[], 'https://en.wikipedia.org/wiki/Rea_Garvey'),
  ('rea-garvey-s-christmas-calling-3a9bb663', 'de', 'Rea Garvey', 'irischer sänger · deutschland', 'Ein irischer Sänger, der in Deutschland lebt. Heute ein Weihnachtskonzert.', array['11 Jahre lang war er Frontmann der Band Reamonn.', 'Seit 2011 solo, vom Rock zum Elektropop.']::text[], 'https://en.wikipedia.org/wiki/Rea_Garvey'),
  ('uche-yara-bodyscanner-tour-2026-b773352d', 'tr', 'Uche Yara', 'şarkıcı ve yapımcı · avusturya', 'Berlin''de yaşayan Avusturyalı şarkıcı. Şarkılarını kendisi yazıyor, çalıyor ve üretiyor.', array['Birden fazla enstrüman çalıyor.', 'Yapımcılığını da kendisi yapıyor.']::text[], 'https://en.wikipedia.org/wiki/Uche_Yara'),
  ('uche-yara-bodyscanner-tour-2026-b773352d', 'en', 'Uche Yara', 'singer and producer · austria', 'An Austrian singer who lives in Berlin. She writes, plays and produces her songs herself.', array['She plays several instruments.', 'She produces her own records.']::text[], 'https://en.wikipedia.org/wiki/Uche_Yara'),
  ('uche-yara-bodyscanner-tour-2026-b773352d', 'de', 'Uche Yara', 'sängerin und produzentin · österreich', 'Österreichische Sängerin, die in Berlin lebt. Sie schreibt, spielt und produziert ihre Songs selbst.', array['Sie spielt mehrere Instrumente.', 'Ihre Platten produziert sie selbst.']::text[], 'https://en.wikipedia.org/wiki/Uche_Yara'),
  ('bob-dylan-fe325521', 'tr', 'Bob Dylan', 'şarkıcı ve söz yazarı · abd', 'Tüm zamanların en büyük söz yazarlarından sayılan isim. 69 yıllık bir kariyer.', array['1960''ların folk müziğine klasik edebiyatın ve şiirin derinliğini getirdi.', 'Sözleri siyasetten felsefeye uzanıyor; yükselen karşı kültüre hitap etti.']::text[], 'https://en.wikipedia.org/wiki/Bob_Dylan'),
  ('bob-dylan-fe325521', 'en', 'Bob Dylan', 'singer-songwriter · usa', 'Counted among the greatest songwriters of all time. A career of 69 years.', array['He brought the depth of classic literature and poetry into the folk music of the early 1960s.', 'His lyrics reach from politics to philosophy; they spoke to the rising counterculture.']::text[], 'https://en.wikipedia.org/wiki/Bob_Dylan'),
  ('bob-dylan-fe325521', 'de', 'Bob Dylan', 'singer-songwriter · usa', 'Gilt als einer der größten Songwriter aller Zeiten. Eine Karriere von 69 Jahren.', array['Er brachte die Tiefe klassischer Literatur und Lyrik in den Folk der frühen 1960er.', 'Seine Texte reichen von Politik bis Philosophie; sie sprachen die aufkommende Gegenkultur an.']::text[], 'https://en.wikipedia.org/wiki/Bob_Dylan'),
  ('ivo-martin-mit-dir-wird-mir-warm-tour-2026-7138f8a6', 'tr', 'Ivo Martin', 'alman indie-pop şarkıcısı', null, '{}'::text[], 'https://de.wikipedia.org/wiki/Ivo_Martin'),
  ('ivo-martin-mit-dir-wird-mir-warm-tour-2026-7138f8a6', 'en', 'Ivo Martin', 'german indie-pop singer', null, '{}'::text[], 'https://de.wikipedia.org/wiki/Ivo_Martin'),
  ('ivo-martin-mit-dir-wird-mir-warm-tour-2026-7138f8a6', 'de', 'Ivo Martin', 'deutscher indie-pop-sänger', null, '{}'::text[], 'https://de.wikipedia.org/wiki/Ivo_Martin'),
  ('alex-stoldt-quasi-nichts-81dd38cd', 'tr', 'Alex Stoldt', 'alman stand-up komedyeni', null, '{}'::text[], 'https://de.wikipedia.org/wiki/Alex_Stoldt'),
  ('alex-stoldt-quasi-nichts-81dd38cd', 'en', 'Alex Stoldt', 'german stand-up comedian', null, '{}'::text[], 'https://de.wikipedia.org/wiki/Alex_Stoldt'),
  ('alex-stoldt-quasi-nichts-81dd38cd', 'de', 'Alex Stoldt', 'deutscher stand-up-comedian', null, '{}'::text[], 'https://de.wikipedia.org/wiki/Alex_Stoldt')
) as v(slug, lang, name, kicker, who, facts, source_url)
join public.events e on e.slug = v.slug
on conflict (event_id, lang) do update
  set name = excluded.name, kicker = excluded.kicker, who = excluded.who,
      facts = excluded.facts, source_url = excluded.source_url, made_at = now();

select count(*) as about_rows from public.event_about;
